//
// Created by Tusse on 25/08/2018.
//

#ifndef CHECKIN_STATES_H
#define CHECKIN_STATES_H

enum States
{
    CONNECTION_CLOSE = -1,
    DISCONNECTED = 0,
    CONNECTED = 1,
    TICKET_CHECKED_OK = 2,
    TICKET_CHECKED_KO = 3,
    LUGGAGES_CHECKED = 4,
    LUGGAGES_DATA_SAVING = 5
};

#endif //CHECKIN_STATES_H
